args:
  time: 10:00:00	                    # Wall clock time limit.
  nodes: 1  #3 | 1                    # Number of nodes to be used.
  ntasks: 2  #3 | 2                   # Number of tasks to be launched.
  ntasks_per_node: 2	#1 | 2          # Maximum count (<= 28 and <= 40 resp.) of tasks per node.
  cpus_per_task: 4	#4                # Number of CPUs required per (MPI-)task.
  mem_per_gpu: 35000                  # Minimum Memory required per allocated GPU.
  mail_type: ALL                      # Notify user by email when certain event types occur. Valid type values are NONE, BEGIN, END, FAIL, REQUEUE, ALL.
  mail_user: mail@domain.xx       	  # The specified mail-address receives email notification of state changes as defined by --mail-type.
  output: scripts/stdout.txt          # File in which job output is stored.
  error: scripts/stderr.txt           # File in which job error messages are stored.
  job_name: TRAINING     	            # Job name.
  partition: gpu_8    	              # Request a specific queue for the resource allocation.
  gres: gpu:1                         # Number of gpus: gpu:3
  
  job: /home/kit/stud/uerib/SyntheticImageGeneration/scripts/run_train_text2image.sh
  
  # salloc
  #/home/kit/stud/uerib/SyntheticImageGeneration/scripts/run_rendevouz.sh
  #/home/kit/stud/uerib/SyntheticImageGeneration/scripts/run_train_text2image.sh
  #/home/kit/stud/uerib/SyntheticImageGeneration/scripts/run_data_preparation.sh
  #/home/kit/stud/uerib/SyntheticImageGeneration/scripts/run_ray_param_tuning.sh
  #/home/kit/stud/uerib/SyntheticImageGeneration/scripts/run_test_text2image.sh