args:
  time: 20:00:00	                    # Wall clock time limit.
  nodes: 1                            # Number of nodes to be used.
  ntasks: 2                           # Number of tasks to be launched.
  ntasks_per_node: 2	                # Maximum count (<= 28 and <= 40 resp.) of tasks per node.
  cpus_per_task: 4	                  # Number of CPUs required per (MPI-)task.
  mem_per_gpu: 35000                  # Minimum Memory required per allocated GPU.
  mail_type: ALL                      # Notify user by email when certain event types occur. Valid type values are NONE, BEGIN, END, FAIL, REQUEUE, ALL.
  mail_user: 'your-email@account'     # The specified mail-address receives email notification of state changes as defined by --mail-type.
  output: scripts/stdout.txt          # File in which job output is stored.
  error: scripts/stderr.txt           # File in which job error messages are stored.
  job_name: TEST       	              # Job name.
  partition: gpu_8    	              # Request a specific queue for the resource allocation.
  gres: gpu:1                         # Number of gpus: gpu:3
  
  job: ./scripts/run_rendevouz.sh
  
  # salloc
  #./scripts/run_rendevouz.sh
  #./scripts/run_train_text2image.sh
  #./scripts/run_data_preparation.sh
  #./scripts/run_ray_param_tuning.sh
  #./scripts/run_test_text2image.sh