client_config_backend: settings
client_config:
  client_id: 435032651600-b6gnsj5ag669d62k7vrv7u9mr39pb55f.apps.googleusercontent.com
  client_secret: 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
save_credentials: True 
save_credentials_backend: client_secrets.json
save_credentials_file: credentials.json 
get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive.file