## Conductor

# Model
model:
  model_type: Imagen # Imagen, ElucidatedImagen, Dalle2

# Trainer
trainer:
  use_existing_model: False
  PATH_MODEL_CHECKPOINT: imagen_checkpoint.pt
  PATH_MODEL_SAVE: ./src/assets/imagen/models/imagen_model_u2.pt
  PATH_MODEL_LOAD: ./src/assets/imagen/models/imagen_model_u1_best.pt

  # Imagen Trainer
  split_valid_from_train: False
  dl_tuple_output_keywords_names:
    - images
    - text_embeds

  # Dataloader
  shuffle: True
  #num_workers: 0
  batch_size: 16 # max.16 for stud01 VM on server - otherwise gpu (32GB) storage not sufficient for unet2
  train_split: 0.9
  valid_split: 0.1
  
  # Training
  max_epochs: 100
  unet_number: 2 # train unet 1 or 2
  param_tuning: False
  early_stopping:
    usage: False
    threshold: 1.0e-8
    queue_length: 20


# Validation
validation:
  PATH_MODEL_VALIDATION: ./src/assets/imagen/models/imagen_checkpoint.pt
  PATH_TRAINING_SAMPLE: ./results/training/

  interval:
    valid_loss: 20
    validate_model: 1000000

  # Sampling
  display_samples: True
  sample_quantity: 5
  sample_seed: 50


# Testing
testing:
  PATH_MODEL_TESTING: ./src/assets/imagen/models/imagen_model_u2_dtp95_best.pt
  PATH_TEST_SAMPLE: ./results/testing/
  
  # Sampling
  unet_number: 2
  sample_quantity: 10000
  sample_seed: 1
  save_samples: False
  save_image_tensors: True
  only_triplets: True
  cond_scale: 5

  # Frechet Inception Distance
  FrechetInceptionDistance:
    usage: True
    feature: 2048
    reset_real_features: True
    normalize: True

  # Kernel Inception Distance
  KernelInceptionDistance:
    usage: True
    feature: 2048
    subsets: 10
    subset_size: 1000
    reset_real_features: True
    normalize: True

