## Training
# Trainer
trainer:
  use_existing_model: True
  PATH_MODEL_CHECKPOINT: ./src/assets/imagen/models/imagen_checkpoint.pt
  PATH_MODEL_SAVE: ./src/assets/imagen/models/imagen_checkpoint.pt

  split_valid_from_train: False
  dl_tuple_output_keywords_names:
    - images
    - text_embeds

  # Dataloader
  shuffle: True
  batch_size: 16 # max.16 for stud01 VM on server - otherwise gpu (32GB) storage not sufficient for unet2
  train_split: 0.95
  valid_split: 0.05
  
  # Training
  max_epochs: 10000
  unet_number: 2 # train unet 1 or 2

data:
  dataset: CholecT45 #CholecT45, CholecSeg8k
  image_size: 480
  use_existing_data_files: True

  # CholecT45 Dataset
  CholecT45:

    fps: 1

    # CholecT45 [RAW]
    PATH_TRIPLETS_DIR: ./data/CholecT45/triplet/
    PATH_DICT_DIR: ./data/CholecT45/dict/
    PATH_VIDEO_DIR: ./data/CholecT45/data/

  # Text embedding [PREPROCESSING]
    PATH_T5_EMBEDDING_FILE: ./src/assets/imagen/text_embeddings/CholecT45/t5_unique_embeds.pkl
    PATH_OHE_EMBEDDING_FILE: ./src/assets/imagen/text_embeddings/CholecT45/ohe_embeds.pkl
    PATH_TRIPLETS_DF_FILE: ./src/assets/imagen/triplets/CholecT45/df_triplets.json

  # CholecSeg8k Dataset
  CholecSeg8k:

    fps: 25

    # CholecSeg8k [RAW]
    PATH_VIDEO_DIR: ./data/CholecSeg8k/

    # Text embedding [PREPROCESSING]
    PATH_T5_EMBEDDING_FILE: ./src/assets/imagen/text_embeddings/CholecSeg8k/t5_unique_embeds.pkl
    PATH_OHE_EMBEDDING_FILE: ./src/assets/imagen/text_embeddings/CholecSeg8k/ohe_embeds.pkl
    PATH_TRIPLETS_DF_FILE: ./src/assets/imagen/triplets/CholecSeg8k/df_triplets.json
  
  Cholec80:

    PATH_PHASE_LABELS: ./


# Validation
validation:
  PATH_MODEL_VALIDATION: ./src/assets/imagen/models/imagen_checkpoint.pt
  PATH_TRAINING_SAMPLE: ./results/training_sample/

# Testing
testing:
  PATH_MODEL_TESTING: ./src/assets/imagen/models/imagen_checkpoint.pt
  PATH_TEST_SAMPLE: ./results/test_sample/
  
  unet_number: 2
  frame_indices: 
  # list of int
    - 50087
    - 60012
    - 70003
    - 90003
    - 31023
    - 11023


## Architecture
# U-Net 1
unet1:
  dim: 32
  cond_dim: 512
  dim_mults: 
    - 1
    - 2
    - 4
    - 8
  num_resnet_blocks: 3
  layer_attns:
    - False
    - True
    - True
    - True
  layer_cross_attns: 
    - False
    - True
    - True
    - True

# U-Net 2
unet2:
  dim: 32
  cond_dim: 512
  dim_mults: 
    - 1
    - 2
    - 4
    - 8
  num_resnet_blocks:
    - 2
    - 4
    - 8
    - 8
  layer_attns:
    - False
    - False
    - False
    - True
  layer_cross_attns: 
    - False
    - False
    - False
    - True

# Imagen
imagen:
  # Parameter
  image_sizes:
    - 64
    - 256
  
  # Text Embedding
  text_embed_dim: 29 #T5: 768 | OHE: 29
  text_encoder_name: ohe_encoder # T5: google/t5-v1_1-base | OHE: ohe_encoder
  
  # Variables
  timesteps: 1000
  cond_drop_prob: 0.1
  loss_type: l2
  noise_schedules: cosine
  pred_objectives: noise
  lowres_noise_schedule: linear
  lowres_sample_noise_level: 0.2
  p2_loss_weight_gamma: 0.5
  p2_loss_weight_k: 1
  only_train_unet_number: 1
  dynamic_thresholding_percentile: 0.95


