## Training
# Trainer
trainer:
  use_existing_model: True
  PATH_MODEL_CHECKPOINT: imagen_checkpoint.pt
  PATH_MODEL_SAVE: ./src/assets/imagen/models/imagen_model.pt
  PATH_MODEL_LOAD: ./src/assets/imagen/models/imagen_model.pt

  # Imagen Trainer
  split_valid_from_train: False
  dl_tuple_output_keywords_names:
    - images
    - text_embeds

  # Dataloader
  shuffle: True
  batch_size: 16 # max.16 for stud01 VM on server - otherwise gpu (32GB) storage not sufficient for unet2
  train_split: 0.90
  valid_split: 0.10
  
  # Training
  max_epochs: 20000
  unet_number: 2 # train unet 1 or 2
  param_tuning: False
  early_stopping:
    usage: True
    threshold: 1.0e-7
    queue_length: 20

## Data
data:
  dataset: Both # CholecT45, CholecSeg8k, Both
  image_size: 480
  use_existing_data_files: True

  # CholecT45 Dataset
  CholecT45:

    fps: 1

    # CholecT45 [RAW]
    PATH_TRIPLETS_DIR: ./data/CholecT45/triplet/
    PATH_DICT_DIR: ./data/CholecT45/dict/
    PATH_VIDEO_DIR: ./data/CholecT45/data/

    # Text embedding [PREPROCESSING]
    PATH_T5_EMBEDDING_FILE: ./src/assets/imagen/text_embeddings/CholecT45/t5_unique_embeds.pkl
    PATH_OHE_EMBEDDING_FILE: ./src/assets/imagen/text_embeddings/CholecT45/ohe_embeds.pkl
    PATH_TRAIN_DF_FILE: ./src/assets/imagen/train/CholecT45/df_triplets.json

  # CholecSeg8k Dataset
  CholecSeg8k:

    fps: 25
    single_classes: True
    multi_classes: True

    # CholecSeg8k [RAW]
    PATH_VIDEO_DIR: ./data/CholecSeg8k/

    # Frame segments [PREPARATION]
    classes:
      # 0
      black background: # black background
        - '#7F7F7F'
      # 1
      abdominal wall cavity: # abdominall wall
        - '#D28C8C'
      # 2
      liver: # liver
        - '#FF7272'
      # 3
      gut: # gastrointestinal tract
        - '#E7469C'
      # 4
      omentum: # fat 
        - '#BAB746'
        - '#BAB74B'
      # 5
      grasper: # grasper 
        - '#AAFF00'
      # 6
      adhesion: # connective tissue
        - '#FF5500'
      # 7
      fluid: # blood
        - '#FF0000'
      # 8
      cystic duct: # cystic duct
        - '#FFFF00'
      # 9
      hook: 
        - '#A9FFB8'
      # 10
      gallbladder: # gallbladder
        - '#FFA0A5'
      # 11
      blood vessel: # hepatic vein
        - '#003280'
      # 12
      liver ligament: 
        - '#6F4A00'
      # 13
      white frame: 
        - '#FFFFFF'

    multi_classes:
      # 
      gallbladder and liver:
        - gallbladder
        - liver

      gallbladder and grasper:
        - gallbladder
        - grasper

      gallbladder and hoook:
        - gallbladder
        - hook

      gallbladder and liver and grasper:
        - gallbladder
        - liver
        - grasper

      gallbladder and liver and hook:
        - gallbladder
        - liver
        - hook
      
      abdominal wall cavity and omentum:
        - abdominal wall cavity
        - omentum

      abdominal wall cavity and omentum and liver:
        - abdominal wall cavity
        - omentum
        - liver

      abdominal wall cavity and adhesion:
        - abdominal wall cavity
        - adhesion
      
      omentum and liver:
        - omentum
        - liver

      gallbladder and omentum:
        - gallbladder
        - omentum

    # Text embedding [PREPROCESSING]
    PATH_T5_EMBEDDING_FILE: ./src/assets/imagen/text_embeddings/CholecSeg8k/t5_unique_embeds.pkl
    PATH_OHE_EMBEDDING_FILE: ./src/assets/imagen/text_embeddings/CholecSeg8k/ohe_embeds.pkl
    PATH_TRAIN_DF_FILE: ./src/assets/imagen/train/CholecSeg8k/df_train.json

  # Cholec80 Dataset
  Cholec80:

    fps: 25
    use_phase_labels: True

    # Cholec80 [RAW]
    PATH_PHASE_LABELS: ./data/Cholec80/phase_annotations/
    PATH_VIDEO_DIR: ./data/Cholec80/videos/

    # Text embedding [PREPROCESSING]
    classes:
      Preparation:                preparation
      CalotTriangleDissection:    calot triangle dissection
      ClippingCutting:            clipping cutting
      GallbladderDissection:      gallbladder dissection
      GallbladderPackaging:       gallbladder packaging
      CleaningCoagulation:        cleaning coagulation
      GallbladderRetraction:      gallbladder etraction

# Validation
validation:
  PATH_MODEL_VALIDATION: ./src/assets/imagen/models/imagen_checkpoint.pt
  PATH_TRAINING_SAMPLE: ./results/training/

  interval:
    valid_loss: 50
    validate_model: 1000

  # Sampling
  display_samples: True
  sample_quantity: 100
  sample_seed: 20

# Testing
testing:
  PATH_MODEL_TESTING: ./src/assets/imagen/models/imagen_model.pt
  PATH_TEST_SAMPLE: ./results/test/
  
  # Sampling
  unet_number: 2
  sample_quantity: 500
  sample_seed: 10
  save_samples: True
  only_triplets: True

  # Frechet Inception Distance
  FrechetInceptionDistance:
    fid_features: 2048
    reset_real_features: False


## Architecture
# U-Net 1
unet1:
  dim: 32
  cond_dim: 512
  dim_mults: 
    - 1
    - 2
    - 4
    - 8
  num_resnet_blocks: 3
  layer_attns:
    - False
    - True
    - True
    - True
  layer_cross_attns: 
    - False
    - True
    - True
    - True

# U-Net 2
unet2:
  dim: 32
  cond_dim: 512
  dim_mults: 
    - 1
    - 2
    - 4
    - 8
  num_resnet_blocks:
    - 2
    - 4
    - 8
    - 8
  layer_attns:
    - False
    - False
    - False
    - True
  layer_cross_attns: 
    - False
    - False
    - False
    - True

# Imagen
imagen:

  # Parameter
  image_sizes:
    - 64
    - 256

  # Text Embedding
  text_embed_dim: 768 #T5: 768 | OHE: 29 (with phase label: 36)
  text_encoder_name: google/t5-v1_1-base # T5: google/t5-v1_1-base | OHE: ohe_encoder

  # Variables
  timesteps: 1000
  cond_drop_prob: 0.1
  loss_type: l2
  noise_schedules: cosine # cosine
  pred_objectives: noise # noise
  lowres_noise_schedule: linear # linear
  lowres_sample_noise_level: 0.2
  p2_loss_weight_gamma: 0.5
  p2_loss_weight_k: 1
  only_train_unet_number: 2 # None
  dynamic_thresholding_percentile: 0.95 # 0.95