## RAY TUNING

# ray tune parameters
tune_params:
  scheduler:
    max_t: 1400 # max_num_epochs
    grace_period: 300 # Only stop trials at least this old in time.
    reduction_factor: 2 
  resources:
    cpu: 4 # cpus_per_trial
    gpu: 1 # gpus_per_trial
  num_samples: -1
  time_budget_s: 160000 # if num_samples = -1
  metric: valid_loss
  mode: min

  local_dir: "./results/tuning"
  run_name: "experiment_"

# Search Space
search_space:
  
  ##
  model:
    model_type:
      function: ray.tune.choice
      values:
        - Imagen
        # - ElucidatedImagen
        # - dall_e2

  ##
  data:
    dataset: 
      function: ray.tune.choice
      values:
        - Both
        - CholecT45
        #- CholecSeg8k

    use_existing_data_files:
      values: True

    use_phase_labels: 
      function: ray.tune.choice
      values:
        - True
        - False

  ##
  imagen:
    # Fixed Params
    image_sizes:
      values:
        - 64
        - 256
    
    # Text Embedding
    text_embed_dim: 
      values: 768
    text_encoder_name: 
      values: google/t5-v1_1-base

    ## Start of Model Tuning Params --------------------------------------------
    # 1: number of ...
    timesteps: 
      function: ray.tune.qrandint
      values:
        lower: 800
        q: 200
        upper: 1400
    # 2
    cond_drop_prob: 
      function: ray.tune.quniform
      values:
        lower: 0.1
        q: 0.1
        upper: 0.4
    # 3
    loss_type:
      function: ray.tune.choice
      values:
        #- l1
        - l2
        #- huber
    # 4
    noise_schedules: 
      function: ray.tune.choice
      values:
        #- cosine
        - linear
    # 5
    pred_objectives:
      function: ray.tune.choice
      values:
        - noise
        #- x_start
        #- v
    # 6
    lowres_noise_schedule:
      function: ray.tune.choice
      values:
        - linear
    # 7
    lowres_sample_noise_level: 
      function: ray.tune.quniform
      values:
        lower: 0.2
        q: 0.1
        upper: 0.4
    # 8
    p2_loss_weight_gamma: 
      function: ray.tune.choice
      values:
        - 0.5
        #- 1
    # 9
    p2_loss_weight_k:
      function: ray.tune.choice
      values:
        - 1
    # 10
    only_train_unet_number:
      function: ray.tune.choice
      values: 
        - 1
        #- 2
        #- None

    # 11
    dynamic_thresholding_percentile: 
      function: ray.tune.quniform
      values:
        lower: 0.5
        q: 0.1
        upper: 1
  