## RAY TUNING

# ray tune parameters
tune_params:
  scheduler:
    max_t: 1000 # max_num_epochs
    grace_period: 100
    reduction_factor: 2
  resources:
    cpu: 4 # cpus_per_trial
    gpu: 1 # gpus_per_trial
  num_samples: -1
  time_budget_s: 3600 # if num_samples = -1
  metric: loss
  mode: min

# Search Space
search_space:
  # Fixed Params
  image_sizes:
    values:
      - 64
      - 256
  
  # Text Embedding
  text_embed_dim: 
    values: 768
  text_encoder_name: 
    values: google/t5-v1_1-base

  ## Start of Tuning Params --------------------------------------------
  # 1: number of ...
  timesteps: 
    function: ray.tune.qrandint
    values:
      lower: 100
      q: 100
      upper: 1500
  # 2
  cond_drop_prob: 
    function: ray.tune.quniform
    values:
      lower: 0.01
      q: 0.01
      upper: 0.2
  # 3
  loss_type:
    function: ray.tune.choice
    values:
      - l1
      - l2
      - huber
  # 4
  noise_schedules: 
    function: ray.tune.choice
    values:
      - cosine
  # 5
  pred_objectives:
    function: ray.tune.choice
    values:
      - noise
  # 6
  lowres_noise_schedule:
    function: ray.tune.choice
    values:
      - linear
  # 7
  lowres_sample_noise_level: 
    function: ray.tune.quniform
    values:
      lower: 0.1
      q: 0.1
      upper: 0.3
  # 8
  p2_loss_weight_gamma: 
    function: ray.tune.quniform
    values:
      lower: 0.4
      q: 0.1
      upper: 0.6
  # 9
  p2_loss_weight_k:
    function: ray.tune.quniform
    values:
      lower: 0.9
      q: 0.1
      upper: 1.1
  # 10
  only_train_unet_number:
    function: ray.tune.choice
    values: 
      - 1 
  # 11
  dynamic_thresholding_percentile: 
    function: ray.tune.quniform
    values:
      lower: 0.5
      q: 0.05
      upper: 1