# * @SimeonAllmendinger
theme: minima
#title: About the generation of synthetic laparascopic images using diffusion-based models
email: simeon.allmendinger@uni-bayreuth.de
description: Using diffusion-based generative models, we were able to produce synthetic laparascopic images and investigate their value for CV-enabled surgical applications.
# url: ""
#github_username:  SimeonAllmendinger
